### ISSUE TITLE
panic: Not implemented

### ISSUE THREAD

**Issue by 0xERR0R** [smhanov/dawg#1]
I tried your library, maybe I did something wrong, please give me an advice: I get "panic: Not implemented". This is my code

```
	sort.Strings(cache)

	b:= dawg.New()

	for _, c := range cache {
		b.Add(c)
	}

	return b.Finish()
```

cache is a string slice with 10M strings (domain names). 

Stacktrace:
```
panic: Not implemented: 10000001

goroutine 3 [running]:
log.Panicf(0x9d2ba7, 0x13, 0xc000159930, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:358 +0xdd
github.com/smhanov/dawg.unsignedLength(0x989681, 0x0)
        /home/x/go/pkg/mod/github.com/smhanov/dawg@v0.0.0-20201027134228-64393ae07b2f/disk.go:511 +0x130
github.com/smhanov/dawg.(*dawg).Write(0xc00014c000, 0xa11fe0, 0xc1151ea000, 0x0, 0x0, 0x0)
        /home/x/go/pkg/mod/github.com/smhanov/dawg@v0.0.0-20201027134228-64393ae07b2f/disk.go:113 +0x514
github.com/smhanov/dawg.(*dawg).Finish(0xc00014c000, 0x0, 0x0)
        /home/x/go/pkg/mod/github.com/smhanov/dawg@v0.0.0-20201027134228-64393ae07b2f/dawg.go:228 +0x250
```

EDIT: Tested with 200K list -> same result

**Comment by smhanov** [comment]
I only implemented writing the "7code" numbers up to 21 bits long. All that
is required is to add an extra clause to these methods in disk.go. You can
do it if you need it urgently.

These are the methods that you need to change. You would need another else
if that follows the same pattern. The 7code format is defined at the top of
disk.go.
func writeUnsigned(w *bitWriter, n uint64) {
if n < 0x7f {
w.WriteBits(n, 8)
} else if n < 0x3fff {
w.WriteBits((n>>7)&0x7f|0x80, 8)
w.WriteBits(n&0x7f, 8)
} else if n < 0x1fffff {
w.WriteBits((n>>14)&0x7f|0x80, 8)
w.WriteBits((n>>7)&0x7f|0x80, 8)
w.WriteBits(n&0x7f, 8)
} else {
// could go further
log.Panic("Not implemented")
}
}


func unsignedLength(n uint64) uint64 {
if n < 0x7f {
return 1
} else if n < 0x3fff {
return 2
} else if n < 0x1fffff {
return 3
}
log.Panicf("Not implemented: %d", n)
return 0
}

**Comment by 0xERR0R** [comment]
ok, thanks. I changed these 2 functions and it works now like a charm
